### ISSUE TITLE
开启后台持续定位时报错 lateinit property watchClient has not been initialized

### ISSUE THREAD

**Issue by gaoyueban** [Spicely/amap_location_muka#2]
这是所有的报错内容
![image](https://user-images.githubusercontent.com/49631411/221249981-1d30cac0-c168-4cd9-bbb5-dcb28a5ab5fe.png)
这里是我的代码
![image](https://user-images.githubusercontent.com/49631411/221250268-c3bf5a85-17c5-46f1-9346-0608d0b3ff55.png)

**Comment by Spicely** [comment]
更新到0.1.8版本 还是不行更新flutter到最新版本
