### ISSUE TITLE
持续定位BUG , 授权定位权限后第一次调用报错, 退出app后在再次打开app可以正常调用持续定位

### ISSUE THREAD

**Issue by 1314LIUhuiGitHub** [Spicely/amap_location_muka#5]
版本信息：Flutter：3.10.6  ， amap_location_muka: ^0.1.9
切换到 amap_location_muka: ^0.1.8也报错
定位授权成功后第一次调用连续定位报错如下：
Failed to handle method call
kotlin.UninitializedPropertyAccessException: lateinit property watchClient has not been initialized
at com.muka.amap_location_muka.AmapLocationMukaPlugin.onMethodCall(AmapLocationMukaPlugin.kt:127)

![image](https://github.com/Spicely/amap_location_muka/assets/36881533/d1afa462-de76-4b04-b6b7-a071db3e2570)

**Comment by Spicely** [comment]
更新到0.1.10版本 注意优先调用方法变更
